spring:
  application:
    name: tx-board-banking-demo

  r2dbc:
    url: r2dbc:h2:mem:///bankdemo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: ""

  data:
    r2dbc:
      repositories:
        enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  packages-to-scan: com.sdlc.pro.txboard.demo.bank.controller
  show-actuator: false

# Spring Tx Board Configuration
sdlc:
  pro:
    spring:
      tx:
        board:
          enable: true
          log-type: DETAILS  # SIMPLE | DETAILS
          alarming-threshold:
            transaction: 500   # ms (small to trigger WARN easily)
            connection: 250    # ms
          duration-buckets: [100, 500, 1000, 2000, 5000]
          storage: IN_MEMORY

# Logging
logging:
  level:
    io.r2dbc.h2: DEBUG
